### ISSUE TITLE
Proposed card solr field types

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/tracc#4]
Proposed card solr field types (without suffixes)

    "card_request_type_ssi" single string, indexed facetted stored
    "card_i_or_p_ssi" single string, indexed facetted stored
    "card_requester_name_ssim" multiple string, indexed facetted stored
    "card_requester_email_ssim" multiple string, indexed facetted stored
    "card_requester_divl_ssim" multiple string, indexed facetted stored
    "card_contact_namesl_ssim" multiple string, stored
    "card_titlel_tsim" multiple text, indexed facetted stored
    "card_short_description_ssi" single string, indexed facetted stored
    "card_prev_workl_tsim" multiple text, stored
    "card_accomplishl_tsim" multiple text, stored
    "card_benefitsl_tsim" multiple text, indexed facetted stored
    "card_goal_alignmentl_tsim" multiple text, indexed facetted stored
    "card_at_stake_tsm" multiple text, stored
    "card_ext_pressure_tsm" multiple text, stored
    "card_non_tech_tsm" multiple text, stored
    "card_time_constraints_tsm" multiple text, stored
    "card_priority_ssi" single string, indexed facetted stored
    "card_sponsor_ssim" multiple string, indexed facetted stored
    "card_more_info_tsm" multiple text, stored
    "card_short_name_ssi" single string, indexed facetted stored
    "card_start_cycle_dtsi" single date, indexed facetted stored
    "card_done_cycle_dtsi" single date, indexed facetted stored
    "card_card_status_tsi" single text, indexed facetted stored
    "card_ext_link_tsm" multiple text, stored
    "card_lit_lead_tsim" multiple text, indexed facetted stored 
    "card_lit_dept_tsim" multiple text, indexed facetted stored
    "card_service_lead_tsim" multiple text, indexed facetted stored 
    "card_other_contacts_tsm" multiple text, stored 
    "card_comments_tsim" multiple text, indexed facetted stored
    "card_recorded_on_dtsi" single date, indexed facetted stored
    "card_created_at_dtsi" single date, indexed facetted stored
    "card_updated_at_dtsi" single date, indexed facetted stored

**Comment by njaffer** [comment]
done
